name: code-review

on:
    pull_request:
        types: [opened, reopened, synchronize]
    workflow_dispatch:

jobs:
    review:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r .github/scripts/requirements.txt
            - name: Get git diff
              run: |
                  git fetch origin "${{github.event.pull_request.base.ref}}"
                  git fetch origin "${{github.event.pull_request.head.ref}}"
                  git diff --unified=0 "origin/${{github.event.pull_request.base.ref}}" > "diff.txt"
            - name: Run Script
              env: 
                OLLAMA_API_URL: ${{ vars.OLLAMA_API_URL }}
              run: python .github/scripts/code_review.py
            - name: output
              id: store
              run: |
                COMMENT=$(sed '/^```/d' res.txt | jq -c .)
                echo "comment=$COMMENT" >> $GITHUB_OUTPUT
                echo $((${{ steps.store.outputs.comment }}))
            - name: Add Pull Request Review Comment
              uses: nbaztec/add-pr-review-comment@v1.0.7
              with:
                comments: ${{ steps.store.outputs.comment }}
                repo-token: ${{ secrets.GITHUB_TOKEN }}
                repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
                allow-repeats: false # This is the default
