name: code-review

on:
    pull_request:
        types: [opened, reopened, synchronize]
    workflow_dispatch:

jobs:
    review:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r .github/scripts/requirements.txt
            - name: Get git diff
              run: |
                  git fetch origin "${{github.event.pull_request.base.ref}}"
                  git fetch origin "${{github.event.pull_request.head.ref}}"
                  git diff --unified=0 "origin/${{github.event.pull_request.base.ref}}" > "diff.txt"
            - name: output
              id: store
              run: |
                COMMENT=$(sed '/^```/d' diff.txt)
                echo "COMMENT<<EOF" >> $GITHUB_ENV
                echo "$COMMENT" >> $GITHUB_ENV
                echo "EOF" >> $GITHUB_ENV
            - name: Add Pull Request Review Comment
              uses: peter-evans/create-or-update-comment@v2
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                repository: ${{ github.repository }}
                issue-number: ${{ github.event.pull_request.number }}
                body: ${{ github.env.comment }}
                edit-mode: replace
