name: code-review

on:
    pull_request:
        types: [opened, reopened, synchronize]
    workflow_dispatch:

jobs:
    review:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Get git diff
              run: |
                  git fetch origin "${{github.event.pull_request.base.ref}}"
                  git fetch origin "${{github.event.pull_request.head.ref}}"
                  git diff --unified=0 "origin/${{github.event.pull_request.base.ref}}" > "diff.txt"
            - name: output
              id: store
              run: |
                COMMENT=$(sed '/^```/d' diff.txt | jq -c .)
                echo "comment=$COMMENT" >> $GITHUB_OUTPUT
                echo "$COMMENT"
            - name: Add Pull Request Review Comment
              uses: nbaztec/github-action-pr-review-comment@v1
              with:
                  comment: ${{ steps.store.outputs.comment }}
                  repo-token: $${{ secrets.GITHUB_TOKEN }}
                  repo-token-user-login: 'github-actions[bot]'
                  allow-repeats: false
